version: '3.8'
services:
  profile-service-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=profile_service
    ports:
      - '5432:5432'
