version: '3.8'
services:
  profile-service-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=profile_service
    ports:
      - '5432:5432'
  elastic-search:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.seed_hosts=es
      - discovery.type=single-node
    ports:
      - '9200:9200'
